// Notepad_plus_msgs.h - Qt port (Plugin API - must be preserved)
#pragma once
#include <windows.h>
enum LangType { L_TEXT, L_PHP, L_C, L_CPP, L_CS, L_OBJC, L_JAVA, L_RC, L_HTML, L_XML, L_MAKEFILE, L_PASCAL, L_BATCH, L_INI, L_ASCII, L_USER, L_ASP, L_SQL, L_VB, L_JS_EMBEDDED, L_CSS, L_PERL, L_PYTHON, L_LUA, L_TEX, L_FORTRAN, L_BASH, L_FLASH, L_NSIS, L_TCL, L_LISP, L_SCHEME, L_ASM, L_DIFF, L_PROPS, L_PS, L_RUBY, L_SMALLTALK, L_VHDL, L_KIX, L_AU3, L_CAML, L_ADA, L_VERILOG, L_MATLAB, L_HASKELL, L_INNO, L_SEARCHRESULT, L_CMAKE, L_YAML, L_COBOL, L_GUI4CLI, L_D, L_POWERSHELL, L_R, L_JSP, L_COFFEESCRIPT, L_JSON, L_JAVASCRIPT, L_FORTRAN_77, L_BAANC, L_SREC, L_IHEX, L_TEHEX, L_SWIFT, L_ASN1, L_AVS, L_BLITZBASIC, L_PUREBASIC, L_FREEBASIC, L_CSOUND, L_ERLANG, L_ESCRIPT, L_FORTH, L_LATEX, L_MMIXAL, L_NIM, L_NNCRONTAB, L_OSCRIPT, L_REBOL, L_REGISTRY, L_RUST, L_SPICE, L_TXT2TAGS, L_VISUALPROLOG, L_TYPESCRIPT, L_JSON5, L_MSSQL, L_GDSCRIPT, L_HOLLYWOOD, L_GOLANG, L_RAKU, L_TOML, L_SAS, L_ERRORLIST, L_EXTERNAL };
enum class ExternalLexerAutoIndentMode { Standard, C_Like, Custom };
enum class MacroStatus { Idle, RecordInProgress, RecordingStopped, PlayingBack };
enum winVer { WV_UNKNOWN, WV_WIN32S, WV_95, WV_98, WV_ME, WV_NT, WV_W2K, WV_XP, WV_S2003, WV_XPX64, WV_VISTA, WV_WIN7, WV_WIN8, WV_WIN81, WV_WIN10, WV_WIN11 };
enum Platform { PF_UNKNOWN, PF_X86, PF_X64, PF_IA64, PF_ARM64 };
#define NPPMSG (WM_USER + 1000)
#define NPPM_GETCURRENTSCINTILLA (NPPMSG + 4)
#define NPPM_GETCURRENTLANGTYPE (NPPMSG + 5)
#define NPPM_SETCURRENTLANGTYPE (NPPMSG + 6)
#define NPPM_GETNBOPENFILES (NPPMSG + 7)
#define ALL_OPEN_FILES 0
#define PRIMARY_VIEW 1
#define SECOND_VIEW 2
#define NPPM_GETNBSESSIONFILES (NPPMSG + 13)
#define NPPM_GETSESSIONFILES (NPPMSG + 14)
#define NPPM_SAVESESSION (NPPMSG + 15)
#define NPPM_SAVECURRENTSESSION (NPPMSG + 16)
#define NPPM_LOADSESSION (NPPMSG + 34)
#define NPPM_CREATESCINTILLAHANDLE (NPPMSG + 20)
#define NPPM_DESTROYSCINTILLAHANDLE_DEPRECATED (NPPMSG + 21)
#define NPPM_GETNBUSERLANG (NPPMSG + 22)
#define NPPM_GETCURRENTDOCINDEX (NPPMSG + 23)
#define MAIN_VIEW 0
#define SUB_VIEW 1
#define NPPM_SETSTATUSBAR (NPPMSG + 24)
#define STATUSBAR_DOC_TYPE 0
#define STATUSBAR_DOC_SIZE 1
#define STATUSBAR_CUR_POS 2
#define STATUSBAR_EOF_FORMAT 3
#define STATUSBAR_UNICODE_TYPE 4
#define NPPM_GETMENUHANDLE (NPPMSG + 25)
#define NPPPLUGINMENU 0
#define NPPMAINMENU 1
#define NPPM_ENCODESCI (NPPMSG + 26)
#define NPPM_DECODESCI (NPPMSG + 27)
#define NPPM_ACTIVATEDOC (NPPMSG + 28)
#define NPPM_LAUNCHFINDINFILESDLG (NPPMSG + 29)
#define NPPM_RELOADFILE (NPPMSG + 36)
#define NPPM_SWITCHTOFILE (NPPMSG + 37)
#define NPPM_SAVECURRENTFILE (NPPMSG + 38)
#define NPPM_SAVEALLFILES (NPPMSG + 39)
#define NPPM_SETMENUITEMCHECK (NPPMSG + 40)
#define NPPM_GETWINDOWSVERSION (NPPMSG + 42)
#define NPPM_MAKECURRENTBUFFERDIRTY (NPPMSG + 44)
#define NPPM_GETPLUGINSCONFIGDIR (NPPMSG + 46)
#define NPPM_MSGTOPLUGIN (NPPMSG + 47)
#define NPPM_MENUCOMMAND (NPPMSG + 48)
#define NPPM_GETNPPVERSION (NPPMSG + 50)
#define NPPM_HIDETABBAR (NPPMSG + 51)
#define NPPM_ISTABBARHIDDEN (NPPMSG + 52)
#define NPPM_GETPOSFROMBUFFERID (NPPMSG + 57)
#define NPPM_GETFULLPATHFROMBUFFERID (NPPMSG + 58)
#define NPPM_GETBUFFERIDFROMPOS (NPPMSG + 59)
#define NPPM_GETCURRENTBUFFERID (NPPMSG + 60)
#define NPPM_RELOADBUFFERID (NPPMSG + 61)
#define NPPM_GETBUFFERLANGTYPE (NPPMSG + 64)
#define NPPM_SETBUFFERLANGTYPE (NPPMSG + 65)
#define NPPM_GETBUFFERENCODING (NPPMSG + 66)
#define NPPM_SETBUFFERENCODING (NPPMSG + 67)
#define NPPM_GETBUFFERFORMAT (NPPMSG + 68)
#define NPPM_SETBUFFERFORMAT (NPPMSG + 69)
#define NPPM_HIDETOOLBAR (NPPMSG + 70)
#define NPPM_ISTOOLBARHIDDEN (NPPMSG + 71)
#define NPPM_HIDEMENU (NPPMSG + 72)
#define NPPM_ISMENUHIDDEN (NPPMSG + 73)
#define NPPM_HIDESTATUSBAR (NPPMSG + 74)
#define NPPM_ISSTATUSBARHIDDEN (NPPMSG + 75)
#define NPPM_GETSHORTCUTBYCMDID (NPPMSG + 76)
#define NPPM_DOOPEN (NPPMSG + 77)
#define NPPM_SAVECURRENTFILEAS (NPPMSG + 78)
#define NPPM_GETCURRENTNATIVELANGENCODING (NPPMSG + 79)
#define NPPM_ALLOCATECMDID (NPPMSG + 81)
#define NPPM_ALLOCATEMARKER (NPPMSG + 82)
#define NPPM_GETLANGUAGENAME (NPPMSG + 83)
#define NPPM_GETLANGUAGEDESC (NPPMSG + 84)
#define NPPM_SHOWDOCLIST (NPPMSG + 85)
#define NPPM_ISDOCLISTSHOWN (NPPMSG + 86)
#define NPPM_GETCURRENTVIEW (NPPMSG + 88)
#define NPPM_SAVEFILE (NPPMSG + 94)
#define NPPM_GETPLUGINHOMEPATH (NPPMSG + 97)
#define NPPM_CREATELEXER (NPPMSG + 110)
#define NPPM_DARKMODESUBCLASSANDTHEME (NPPMSG + 112)
