// Ported to Qt6: Virtual key codes and key constants
// Extracted from keys.h in source
#pragma once

#include <QtCore>

// Virtual key codes matching Win32 VK_* values
namespace NppKeys {
    constexpr quint32 VK_BACK      = 0x08;
    constexpr quint32 VK_TAB       = 0x09;
    constexpr quint32 VK_RETURN    = 0x0D;
    constexpr quint32 VK_SHIFT     = 0x10;
    constexpr quint32 VK_CONTROL   = 0x11;
    constexpr quint32 VK_MENU      = 0x12;  // ALT
    constexpr quint32 VK_ESCAPE    = 0x1B;
    constexpr quint32 VK_SPACE     = 0x20;
    constexpr quint32 VK_END       = 0x23;
    constexpr quint32 VK_HOME      = 0x24;
    constexpr quint32 VK_LEFT      = 0x25;
    constexpr quint32 VK_UP        = 0x26;
    constexpr quint32 VK_RIGHT     = 0x27;
    constexpr quint32 VK_DOWN      = 0x28;
    constexpr quint32 VK_PRINT     = 0x2A;
    constexpr quint32 VK_INSERT    = 0x2D;
    constexpr quint32 VK_DELETE    = 0x2E;
    constexpr quint32 VK_0         = 0x30;
    constexpr quint32 VK_1         = 0x31;
    constexpr quint32 VK_2         = 0x32;
    constexpr quint32 VK_3         = 0x33;
    constexpr quint32 VK_4         = 0x34;
    constexpr quint32 VK_5         = 0x35;
    constexpr quint32 VK_6         = 0x36;
    constexpr quint32 VK_7         = 0x37;
    constexpr quint32 VK_8         = 0x38;
    constexpr quint32 VK_9         = 0x39;
    constexpr quint32 VK_A         = 0x41;
    constexpr quint32 VK_B         = 0x42;
    constexpr quint32 VK_C         = 0x43;
    constexpr quint32 VK_D         = 0x44;
    constexpr quint32 VK_E         = 0x45;
    constexpr quint32 VK_F         = 0x46;
    constexpr quint32 VK_G         = 0x47;
    constexpr quint32 VK_H         = 0x48;
    constexpr quint32 VK_I         = 0x49;
    constexpr quint32 VK_J         = 0x4A;
    constexpr quint32 VK_K         = 0x4B;
    constexpr quint32 VK_L         = 0x4C;
    constexpr quint32 VK_M         = 0x4D;
    constexpr quint32 VK_N         = 0x4E;
    constexpr quint32 VK_O         = 0x4F;
    constexpr quint32 VK_P         = 0x50;
    constexpr quint32 VK_Q         = 0x51;
    constexpr quint32 VK_R         = 0x52;
    constexpr quint32 VK_S         = 0x53;
    constexpr quint32 VK_T         = 0x54;
    constexpr quint32 VK_U         = 0x55;
    constexpr quint32 VK_V         = 0x56;
    constexpr quint32 VK_W         = 0x57;
    constexpr quint32 VK_X         = 0x58;
    constexpr quint32 VK_Y         = 0x59;
    constexpr quint32 VK_Z         = 0x5A;
    constexpr quint32 VK_LWIN      = 0x5B;
    constexpr quint32 VK_RWIN      = 0x5C;
    constexpr quint32 VK_APPS      = 0x5D;
    constexpr quint32 VK_NUMPAD0   = 0x60;
    constexpr quint32 VK_NUMPAD1   = 0x61;
    constexpr quint32 VK_NUMPAD2   = 0x62;
    constexpr quint32 VK_NUMPAD3   = 0x63;
    constexpr quint32 VK_NUMPAD4   = 0x64;
    constexpr quint32 VK_NUMPAD5   = 0x65;
    constexpr quint32 VK_NUMPAD6   = 0x66;
    constexpr quint32 VK_NUMPAD7   = 0x67;
    constexpr quint32 VK_NUMPAD8   = 0x68;
    constexpr quint32 VK_NUMPAD9   = 0x69;
    constexpr quint32 VK_MULTIPLY  = 0x6A;
    constexpr quint32 VK_ADD       = 0x6B;
    constexpr quint32 VK_SEPARATOR = 0x6C;
    constexpr quint32 VK_SUBTRACT  = 0x6D;
    constexpr quint32 VK_DECIMAL   = 0x6E;
    constexpr quint32 VK_DIVIDE    = 0x6F;
    constexpr quint32 VK_F1        = 0x70;
    constexpr quint32 VK_F2        = 0x71;
    constexpr quint32 VK_F3        = 0x72;
    constexpr quint32 VK_F4        = 0x73;
    constexpr quint32 VK_F5        = 0x74;
    constexpr quint32 VK_F6        = 0x75;
    constexpr quint32 VK_F7        = 0x76;
    constexpr quint32 VK_F8        = 0x77;
    constexpr quint32 VK_F9        = 0x78;
    constexpr quint32 VK_F10       = 0x79;
    constexpr quint32 VK_F11       = 0x7A;
    constexpr quint32 VK_F12       = 0x7B;
    constexpr quint32 VK_F13       = 0x7C;
    constexpr quint32 VK_F14       = 0x7D;
    constexpr quint32 VK_F15       = 0x7E;
    constexpr quint32 VK_F16       = 0x7F;
    constexpr quint32 VK_F17       = 0x80;
    constexpr quint32 VK_F18       = 0x81;
    constexpr quint32 VK_F19       = 0x82;
    constexpr quint32 VK_F20       = 0x83;
    constexpr quint32 VK_F21       = 0x84;
    constexpr quint32 VK_F22       = 0x85;
    constexpr quint32 VK_F23       = 0x86;
    constexpr quint32 VK_F24       = 0x87;
    constexpr quint32 VK_NUMLOCK   = 0x90;
    constexpr quint32 VK_SCROLL    = 0x91;
    constexpr quint32 VK_LSHIFT    = 0xA0;
    constexpr quint32 VK_RSHIFT    = 0xA1;
    constexpr quint32 VK_LCONTROL  = 0xA2;
    constexpr quint32 VK_RCONTROL  = 0xA3;
    constexpr quint32 VK_LMENU     = 0xA4;  // Left ALT
    constexpr quint32 VK_RMENU     = 0xA5;  // Right ALT
    constexpr quint32 VK_OEM_PLUS     = 0xBB;
    constexpr quint32 VK_OEM_COMMA    = 0xBC;
    constexpr quint32 VK_OEM_MINUS    = 0xBD;
    constexpr quint32 VK_OEM_PERIOD   = 0xBE;
    constexpr quint32 VK_OEM_1        = 0xBA;  // ;:
    constexpr quint32 VK_OEM_2        = 0xBF;  // /?
    constexpr quint32 VK_OEM_3        = 0xC0;  // `~
    constexpr quint32 VK_OEM_4        = 0xDB;  // [{
    constexpr quint32 VK_OEM_5        = 0xDC;  // \|
    constexpr quint32 VK_OEM_6        = 0xDD;  // ]}
    constexpr quint32 VK_OEM_7        = 0xDE;  // '"
    constexpr quint32 VK_OEM_8        = 0xDF;
    constexpr quint32 VK_CAPITAL    = 0x14;
    constexpr quint32 VK_PRIOR     = 0x21;  // PAGE UP
    constexpr quint32 VK_NEXT       = 0x22;  // PAGE DOWN
}

// Additional key names
constexpr const char* VK_KEYNAME_BACK      = "Backspace";
constexpr const char* VK_KEYNAME_TAB       = "Tab";
constexpr const char* VK_KEYNAME_RETURN    = "Enter";
constexpr const char* VK_KEYNAME_SHIFT     = "Shift";
constexpr const char* VK_KEYNAME_CONTROL   = "Ctrl";
constexpr const char* VK_KEYNAME_MENU      = "Alt";
constexpr const char* VK_KEYNAME_ESCAPE    = "Escape";
constexpr const char* VK_KEYNAME_SPACE     = "Space";
constexpr const char* VK_KEYNAME_END       = "End";
constexpr const char* VK_KEYNAME_HOME      = "Home";
constexpr const char* VK_KEYNAME_LEFT      = "Left";
constexpr const char* VK_KEYNAME_UP        = "Up";
constexpr const char* VK_KEYNAME_RIGHT     = "Right";
constexpr const char* VK_KEYNAME_DOWN      = "Down";
constexpr const char* VK_KEYNAME_INSERT    = "Insert";
constexpr const char* VK_KEYNAME_DELETE    = "Delete";
constexpr const char* VK_KEYNAME_0         = "0";
constexpr const char* VK_KEYNAME_1         = "1";
constexpr const char* VK_KEYNAME_2         = "2";
constexpr const char* VK_KEYNAME_3         = "3";
constexpr const char* VK_KEYNAME_4         = "4";
constexpr const char* VK_KEYNAME_5         = "5";
constexpr const char* VK_KEYNAME_6         = "6";
constexpr const char* VK_KEYNAME_7         = "7";
constexpr const char* VK_KEYNAME_8         = "8";
constexpr const char* VK_KEYNAME_9         = "9";
constexpr const char* VK_KEYNAME_A         = "A";
constexpr const char* VK_KEYNAME_B         = "B";
constexpr const char* VK_KEYNAME_C         = "C";
constexpr const char* VK_KEYNAME_D         = "D";
constexpr const char* VK_KEYNAME_E         = "E";
constexpr const char* VK_KEYNAME_F         = "F";
constexpr const char* VK_KEYNAME_G         = "G";
constexpr const char* VK_KEYNAME_H         = "H";
constexpr const char* VK_KEYNAME_I         = "I";
constexpr const char* VK_KEYNAME_J         = "J";
constexpr const char* VK_KEYNAME_K         = "K";
constexpr const char* VK_KEYNAME_L         = "L";
constexpr const char* VK_KEYNAME_M         = "M";
constexpr const char* VK_KEYNAME_N         = "N";
constexpr const char* VK_KEYNAME_O         = "O";
constexpr const char* VK_KEYNAME_P         = "P";
constexpr const char* VK_KEYNAME_Q         = "Q";
constexpr const char* VK_KEYNAME_R         = "R";
constexpr const char* VK_KEYNAME_S         = "S";
constexpr const char* VK_KEYNAME_T         = "T";
constexpr const char* VK_KEYNAME_U         = "U";
constexpr const char* VK_KEYNAME_V         = "V";
constexpr const char* VK_KEYNAME_W         = "W";
constexpr const char* VK_KEYNAME_X         = "X";
constexpr const char* VK_KEYNAME_Y         = "Y";
constexpr const char* VK_KEYNAME_Z         = "Z";
constexpr const char* VK_KEYNAME_NUMPAD0   = "Num0";
constexpr const char* VK_KEYNAME_NUMPAD1   = "Num1";
constexpr const char* VK_KEYNAME_NUMPAD2   = "Num2";
constexpr const char* VK_KEYNAME_NUMPAD3   = "Num3";
constexpr const char* VK_KEYNAME_NUMPAD4   = "Num4";
constexpr const char* VK_KEYNAME_NUMPAD5   = "Num5";
constexpr const char* VK_KEYNAME_NUMPAD6   = "Num6";
constexpr const char* VK_KEYNAME_NUMPAD7   = "Num7";
constexpr const char* VK_KEYNAME_NUMPAD8   = "Num8";
constexpr const char* VK_KEYNAME_NUMPAD9   = "Num9";
constexpr const char* VK_KEYNAME_MULTIPLY  = "Multiply";
constexpr const char* VK_KEYNAME_ADD       = "Add";
constexpr const char* VK_KEYNAME_SEPARATOR = "Separator";
constexpr const char* VK_KEYNAME_SUBTRACT  = "Subtract";
constexpr const char* VK_KEYNAME_DECIMAL   = "Decimal";
constexpr const char* VK_KEYNAME_DIVIDE    = "Divide";
constexpr const char* VK_KEYNAME_F1        = "F1";
constexpr const char* VK_KEYNAME_F2        = "F2";
constexpr const char* VK_KEYNAME_F3        = "F3";
constexpr const char* VK_KEYNAME_F4        = "F4";
constexpr const char* VK_KEYNAME_F5        = "F5";
constexpr const char* VK_KEYNAME_F6        = "F6";
constexpr const char* VK_KEYNAME_F7        = "F7";
constexpr const char* VK_KEYNAME_F8        = "F8";
constexpr const char* VK_KEYNAME_F9        = "F9";
constexpr const char* VK_KEYNAME_F10       = "F10";
constexpr const char* VK_KEYNAME_F11       = "F11";
constexpr const char* VK_KEYNAME_F12       = "F12";
constexpr const char* VK_KEYNAME_LWIN      = "LWin";
constexpr const char* VK_KEYNAME_RWIN      = "RWin";
constexpr const char* VK_KEYNAME_APPS      = "Apps";
constexpr const char* VK_KEYNAME_CAPITAL   = "Caps";
constexpr const char* VK_KEYNAME_PRIOR     = "PageUp";
constexpr const char* VK_KEYNAME_NEXT      = "PageDown";
