// AutoCompletion.h - Qt port
#pragma once
#include <QWidget>
#include <vector>
#include <string>
#include "FunctionCallTip.h"
class ScintillaEditView;
struct MatchedCharInserted { MatchedCharInserted() = delete; char _c; size_t _pos; MatchedCharInserted(char c, size_t pos) : _c(c), _pos(pos) {} };
class InsertedMatchedChars { public: void init(ScintillaEditView* pEditView) { _pEditView = pEditView; } void removeInvalidElements(MatchedCharInserted mci); void add(MatchedCharInserted mci); bool isEmpty() const { return _insertedMatchedChars.size() == 0; } intptr_t search(char startChar, char endChar, size_t posToDetect); private: std::vector<MatchedCharInserted> _insertedMatchedChars; ScintillaEditView* _pEditView = nullptr; };
class AutoCompletion { public: explicit AutoCompletion(ScintillaEditView* pEditView) : _pEditView(pEditView), _funcCalltip(pEditView) { _insertedMatchedChars.init(_pEditView); } ~AutoCompletion() {} enum class AutocompleteColorIndex { autocompleteText, autocompleteBg, selectedText, selectedBg, calltipBg, calltipText, calltipHighlight }; bool setLanguage(LangType language); bool showApiComplete(); bool showWordComplete(bool autoInsert); bool showApiAndWordComplete(); bool showFunctionComplete(); void showPathCompletion(); void insertMatchedChars(int character, const MatchedPairConf& matchedPairConf); void update(int character); void callTipClick(size_t direction); void getCloseTag(char* closeTag, size_t closeTagLen, size_t caretPos, bool isHTML) const; static void setColour(COLORREF colour2Set, AutocompleteColorIndex i); static void drawAutocomplete(const ScintillaEditView* pEditView); protected: static COLORREF _autocompleteBg; static COLORREF _autocompleteText; static COLORREF _selectedBg; static COLORREF _selectedText; static COLORREF _calltipBg; static COLORREF _calltipText; static COLORREF _calltipHighlight; private: bool _funcCompletionActive = false; ScintillaEditView* _pEditView = nullptr; LangType _curLang = L_TEXT; void* _pXmlFile = nullptr; void _xmlKeyword{}; bool _isFxImageRegistered = false; bool _isFxImageRegisteredDark = false; InsertedMatchedChars _insertedMatchedChars; bool _ignoreCase = true; std::vector<std::string> _keyWordArray; std::string _keyWords; size_t _keyWordMaxLen = 0; FunctionCallTip _funcCalltip; const wchar_t* getApiFileName(); void getWordArray(std::vector<std::string>& wordArray, const char* beginChars, const char* excludeChars) const; enum AutocompleteType { autocFunc, autocFuncAndWord, autocFuncBrief, autocWord }; bool showAutoComplete(AutocompleteType autocType, bool autoInsert); };
